% Project: Mini Photoshop
% Author: Francesco Albano - LJ2506219
% University: BUAA
% Course: Technical Computing & Programming for Engineers
% Date: 17/12/2025
% Version: v1.0 (final delivery)
% GitHub: https://github.com/fra2404/Mini_Photoshop
% Description: Manages the creation and configuration of the user interface components for the Mini Photoshop application.

classdef UIManager < handle

    properties (Access = public)
        BaseRightPanelWidth
    end

    methods (Static)

        function createMainUI(app)
            % Create UIFigure and components
            UIManager.createUIFigureAndComponents(app);
        end

        function createUIFigureAndComponents(app)

            % Helper function to enforce minimum window size
            function enforceMinSize(fig)
                minWidth = 1200;
                minHeight = 600;
                pos = fig.Position;
                if pos(3) < minWidth
                    pos(3) = minWidth;
                end
                if pos(4) < minHeight
                    pos(4) = minHeight;
                end
                fig.Position = pos;
            end

            % Create UIFigure - NOW RESIZABLE with minimum size
            app.UIFigure = uifigure('Name', 'Mini Photoshop', ...
                'Position', [100 100 1400 800], ...
                'Resize', 'on', ...
                'AutoResizeChildren', 'off', ...
                'Color', [0.95 0.95 0.95], ...
                'CloseRequestFcn', @app.UIFigureCloseRequest, ...
                'SizeChangedFcn', @(src,~) enforceMinSize(src));

            % Menu bar
            fileMenu = uimenu(app.UIFigure, 'Text', '📂 FILE');
            uimenu(fileMenu, 'Text', '🖼️  Open Image...', 'Accelerator', 'O', 'MenuSelectedFcn', @(src, event) app.OpenButtonPushed());
            uimenu(fileMenu, 'Text', '💾 Save Image...', 'Accelerator', 'S', 'MenuSelectedFcn', @(src, event) app.SaveButtonPushed());
            uimenu(fileMenu, 'Separator', 'on', 'Text', '❌ Exit', 'Accelerator', 'Q', 'MenuSelectedFcn', @(src, event) close(app.UIFigure));

            editMenu = uimenu(app.UIFigure, 'Text', '✏️ EDIT');
            uimenu(editMenu, 'Text', '🔄 Reset', 'Accelerator', 'R', 'MenuSelectedFcn', @(src, event) app.ResetButtonPushed());
            uimenu(editMenu, 'Text', '↩️ Undo', 'Accelerator', 'Z', 'MenuSelectedFcn', @(src, event) app.UndoButtonPushed());
            uimenu(editMenu, 'Text', '↪️ Redo', 'Accelerator', 'Y', 'MenuSelectedFcn', @(src, event) app.RedoButtonPushed());

            infoMenu = uimenu(app.UIFigure, 'Text', 'ℹ️ INFO');
            uimenu(infoMenu, 'Text', '🖼️ Photo Info', 'MenuSelectedFcn', @(src, event) app.ShowPhotoInfoWindow());
            uimenu(infoMenu, 'Text', '📝 Modification History', 'MenuSelectedFcn', @(src, event) app.ShowModificationHistoryWindow());

            % ==================== LEFT PANEL: IMAGE + HISTOGRAM ====================
            leftPanel = uipanel(app.UIFigure, ...
                'Units', 'normalized', ...
                'Position', [0.01 0.01 0.57 0.98], ...
                'BackgroundColor', [0.95 0.95 0.95], ...
                'BorderType', 'line', ...
                'HighlightColor', [0.7 0.7 0.7]);

            % UIAxes - Main Image Display (top 70% of left panel)
            app.UIAxes = uiaxes(leftPanel, ...
                'Units', 'normalized', ...
                'Position', [0.02 0.32 0.96 0.66]);
            app.UIAxes.Visible = 'off';
            app.UIAxes.XGrid = 'off';
            app.UIAxes.YGrid = 'off';
            app.UIAxes.Box = 'off';
            app.UIAxes.XTick = [];
            app.UIAxes.YTick = [];
            axis(app.UIAxes, 'tight');
            app.UIAxes.XColor = 'none';
            app.UIAxes.YColor = 'none';

            % PlaceholderImage - mostra camera.png al centro
            app.PlaceholderLabel = uiimage(leftPanel, ...
                'Position', [250 320 300 200], ...
                'ImageSource', 'camera.png', ...
                'ScaleMethod', 'fit');

            % Upload Photo button - sotto l'immagine
            app.OpenButton = uibutton(leftPanel, 'push', ...
                'Text', '📂 Upload Photo', ...
                'Position', [300 280 200 35], ...
                'FontSize', 12, ...
                'FontWeight', 'bold', ...
                'BackgroundColor', [0.2 0.6 1], ...
                'FontColor', [1 1 1], ...
                'ButtonPushedFcn', @app.OpenButtonPushed);

            % HistogramAxes (bottom 28% of left panel)
            app.HistogramAxes = uiaxes(leftPanel, ...
                'Units', 'normalized', ...
                'Position', [0.05 0.02 0.90 0.26]);
            app.HistogramAxes.Visible = 'off';
            title(app.HistogramAxes, 'Histogram');

            % ==================== RIGHT PANEL: CONTROLS (SCROLLABLE) ====================
            rightPanel = uipanel(app.UIFigure, ...
                'Units', 'normalized', ...
                'Position', [0.59 0.01 0.40 0.98], ...
                'BackgroundColor', [0.95 0.95 0.95], ...
                'Scrollable', 'on', ...
                'AutoResizeChildren', 'off');

            % Y position tracking (from top, higher than panel to enable scroll)
            yBase = 2300; % Virtual canvas height
            yPos = 50;    % Start from top with margin

            % === SECTION 1: MAIN BUTTONS ===
            uilabel(rightPanel, 'Text', '═══ MAIN ACTIONS ═══', ...
                'Position', [20 yBase-yPos 520 25], 'FontWeight', 'bold', ...
                'FontSize', 13, 'HorizontalAlignment', 'center', ...
                'BackgroundColor', [0.85 0.90 0.95]);
            yPos = yPos + 50;

            app.ResetButton = uibutton(rightPanel, 'push', 'Text', '🔄 Reset', ...
                'Position', [30 yBase-yPos 115 35], 'BackgroundColor', [1 0.9 0.8], ...
                'FontWeight', 'bold', 'FontSize', 11, ...
                'ButtonPushedFcn', @app.ResetButtonPushed);
            
            app.ShowOriginalButton = uibutton(rightPanel, 'push', 'Text', '👁 Show Original', ...
                'Position', [160 yBase-yPos 150 35], 'BackgroundColor', [1 1 0.8], ...
                'FontWeight', 'bold', 'FontSize', 11, ...
                'ButtonPushedFcn', @app.ShowOriginalButtonPushed);
            
            app.UndoButton = uibutton(rightPanel, 'push', 'Text', '↩️ Undo', ...
                'Position', [325 yBase-yPos 90 35], 'BackgroundColor', [0.9 0.9 0.9], ...
                'FontWeight', 'bold', 'ButtonPushedFcn', @app.UndoButtonPushed);
            
            app.RedoButton = uibutton(rightPanel, 'push', 'Text', '↪️ Redo', ...
                'Position', [430 yBase-yPos 90 35], 'BackgroundColor', [0.9 0.9 0.9], ...
                'FontWeight', 'bold', 'ButtonPushedFcn', @app.RedoButtonPushed);
            yPos = yPos + 20;

            % Separator
            uilabel(rightPanel, 'Text', '', 'Position', [20 yBase-yPos 520 2], 'BackgroundColor', [0.6 0.6 0.6]);
            yPos = yPos + 20;
            
            % Separator
            uilabel(rightPanel, 'Text', '', 'Position', [20 yBase-yPos 520 2], 'BackgroundColor', [0.6 0.6 0.6]);
            yPos = yPos + 20;

            % === SECTION 2: BASIC ADJUSTMENTS ===
            uilabel(rightPanel, 'Text', '═══ BASIC ADJUSTMENTS ═══', ...
                'Position', [20 yBase-yPos 520 25], 'FontWeight', 'bold', ...
                'FontSize', 13, 'HorizontalAlignment', 'center', ...
                'BackgroundColor', [0.85 0.90 0.95]);
            yPos = yPos + 35;

            % Brightness
            app.BrightnessLabel = uilabel(rightPanel, 'Text', 'Brightness', ...
                'Position', [30 yBase-yPos 100 22], 'FontWeight', 'bold', 'FontSize', 11);
            app.BrightnessSlider = uislider(rightPanel, 'Limits', [-100 100], 'Value', 0, ...
                'Position', [140 yBase-yPos+8 250 3], ...
                'ValueChangedFcn', @app.BrightnessSliderValueChanged);
            app.BrightnessField = uieditfield(rightPanel, 'numeric', 'Limits', [-100 100], 'Value', 0, ...
                'Position', [400 yBase-yPos 60 22], ...
                'ValueChangedFcn', @app.BrightnessFieldValueChanged);
            yPos = yPos + 40;

            % Contrast
            app.ContrastLabel = uilabel(rightPanel, 'Text', 'Contrast', ...
                'Position', [30 yBase-yPos 100 22], 'FontWeight', 'bold', 'FontSize', 11);
            app.ContrastSlider = uislider(rightPanel, 'Limits', [-100 100], 'Value', 0, ...
                'Position', [140 yBase-yPos+8 250 3], ...
                'ValueChangedFcn', @app.ContrastSliderValueChanged);
            app.ContrastField = uieditfield(rightPanel, 'numeric', 'Limits', [-100 100], 'Value', 0, ...
                'Position', [400 yBase-yPos 60 22], ...
                'ValueChangedFcn', @app.ContrastFieldValueChanged);
            yPos = yPos + 40;

            % Saturation
            app.SaturationLabel = uilabel(rightPanel, 'Text', 'Saturation', ...
                'Position', [30 yBase-yPos 100 22], 'FontWeight', 'bold', 'FontSize', 11);
            app.SaturationSlider = uislider(rightPanel, 'Limits', [-100 100], 'Value', 0, ...
                'Position', [140 yBase-yPos+8 250 3], ...
                'ValueChangedFcn', @app.SaturationSliderValueChanged);
            app.SaturationField = uieditfield(rightPanel, 'numeric', 'Limits', [-100 100], 'Value', 0, ...
                'Position', [400 yBase-yPos 60 22], ...
                'ValueChangedFcn', @app.SaturationFieldValueChanged);
            yPos = yPos + 45;

            % Separator
            uilabel(rightPanel, 'Text', '', 'Position', [20 yBase-yPos 520 2], 'BackgroundColor', [0.6 0.6 0.6]);
            yPos = yPos + 20;
            
            % Separator
            uilabel(rightPanel, 'Text', '', 'Position', [20 yBase-yPos 520 2], 'BackgroundColor', [0.6 0.6 0.6]);
            yPos = yPos + 20;

            % === SECTION 3: RGB CURVES ===
            uilabel(rightPanel, 'Text', '═══ RGB CURVES ═══', ...
                'Position', [20 yBase-yPos 520 25], 'FontWeight', 'bold', ...
                'FontSize', 13, 'HorizontalAlignment', 'center', ...
                'BackgroundColor', [0.85 0.90 0.95]);
            yPos = yPos + 35;

            % Curve axes
            app.CurveAxes = uiaxes(rightPanel);
            app.CurveAxes.Position = [50 yBase-yPos-350 450 350];
            app.CurveAxes.ButtonDownFcn = @app.CurveAxesButtonDown;
            yPos = yPos + 390;

            % Curve controls
            app.CurveChannelLabel = uilabel(rightPanel, 'Text', 'Channel:', ...
                'Position', [20 yBase-yPos 70 22], 'FontWeight', 'bold');
            app.CurveChannelDropDown = uidropdown(rightPanel, ...
                'Items', {'R', 'G', 'B', 'RGB'}, 'Value', 'RGB', ...
                'Position', [95 yBase-yPos 80 22], ...
                'ValueChangedFcn', @app.CurveChannelDropDownValueChanged);
            
            app.AddPointButton = uibutton(rightPanel, 'push', 'Text', 'Add Point', ...
                'Position', [185 yBase-yPos 90 25], 'BackgroundColor', [0.8 0.9 1], ...
                'ButtonPushedFcn', @app.AddPointButtonPushed);
            
            app.RemovePointButton = uibutton(rightPanel, 'push', 'Text', 'Remove', ...
                'Position', [285 yBase-yPos 90 25], 'BackgroundColor', [1 0.8 0.8], ...
                'ButtonPushedFcn', @app.RemovePointButtonPushed);
            
            app.ResetCurveButton = uibutton(rightPanel, 'push', 'Text', 'Reset Curves', ...
                'Position', [385 yBase-yPos 110 25], 'BackgroundColor', [0.9 0.95 1], ...
                'ButtonPushedFcn', @app.ResetCurveButtonPushed);
            yPos = yPos + 45;

            % Separator
            uilabel(rightPanel, 'Text', '', 'Position', [20 yBase-yPos 520 2], 'BackgroundColor', [0.6 0.6 0.6]);
            yPos = yPos + 20;
            
            % Separator
            uilabel(rightPanel, 'Text', '', 'Position', [20 yBase-yPos 520 2], 'BackgroundColor', [0.6 0.6 0.6]);
            yPos = yPos + 20;

            % === SECTION 4: TRANSFORMATIONS ===
            uilabel(rightPanel, 'Text', '═══ TRANSFORMATIONS ═══', ...
                'Position', [20 yBase-yPos 520 25], 'FontWeight', 'bold', ...
                'FontSize', 13, 'HorizontalAlignment', 'center', ...
                'BackgroundColor', [0.85 0.90 0.95]);
            yPos = yPos + 50;

            % Rotation buttons (3 columns)
            btnW = 110; gap = 20;
            totalW = 3*btnW + 2*gap;
            startX = (560 - totalW) / 2;
            app.Rotate90Button = uibutton(rightPanel, 'push', 'Text', '⟳ 90°', ...
                'Position', [startX yBase-yPos btnW 35], 'BackgroundColor', [0.9 0.95 1], ...
                'FontWeight', 'bold', 'ButtonPushedFcn', @app.Rotate90ButtonPushed);
            app.Rotate180Button = uibutton(rightPanel, 'push', 'Text', '⟳ 180°', ...
                'Position', [startX+btnW+gap yBase-yPos btnW 35], 'BackgroundColor', [0.9 0.95 1], ...
                'FontWeight', 'bold', 'ButtonPushedFcn', @app.Rotate180ButtonPushed);
            app.Rotate270Button = uibutton(rightPanel, 'push', 'Text', '⟳ 270°', ...
                'Position', [startX+2*(btnW+gap) yBase-yPos btnW 35], 'BackgroundColor', [0.9 0.95 1], ...
                'FontWeight', 'bold', 'ButtonPushedFcn', @app.Rotate270ButtonPushed);
            yPos = yPos + 50;

            % Flip buttons
            btnW2 = 150; gap2 = 30;
            totalW2 = 2*btnW2 + gap2;
            startX2 = (560 - totalW2) / 2;
            app.FlipHorizontalButton = uibutton(rightPanel, 'push', 'Text', '⇄ Flip Horizontal', ...
                'Position', [startX2 yBase-yPos btnW2 35], 'BackgroundColor', [1 0.95 0.9], ...
                'FontWeight', 'bold', 'ButtonPushedFcn', @app.FlipHorizontalButtonPushed);
            app.FlipVerticalButton = uibutton(rightPanel, 'push', 'Text', '⇅ Flip Vertical', ...
                'Position', [startX2+btnW2+gap2 yBase-yPos btnW2 35], 'BackgroundColor', [1 0.95 0.9], ...
                'FontWeight', 'bold', 'ButtonPushedFcn', @app.FlipVerticalButtonPushed);
            yPos = yPos + 20;

            % Separator
            uilabel(rightPanel, 'Text', '', 'Position', [20 yBase-yPos 520 2], 'BackgroundColor', [0.6 0.6 0.6]);
            yPos = yPos + 20;

            % === SECTION 5: FILTERS ===
            uilabel(rightPanel, 'Text', '═══ FILTERS ═══', ...
                'Position', [20 yBase-yPos 520 25], 'FontWeight', 'bold', ...
                'FontSize', 13, 'HorizontalAlignment', 'center', ...
                'BackgroundColor', [0.85 0.90 0.95]);
            yPos = yPos + 40;

            % Filter grid: 3 rows (3+3+2)
            imgW = 110; imgH = 82; btnH = 20; labelH = 16;
            colGap = 25; rowGap = 20;
            
            % ROW 1: 3 filters (Blur, Sharpen, Sobel)
            totalW1 = 3*imgW + 2*colGap;
            startX1 = (560 - totalW1) / 2;
            
            app.FilterGaussianBlurImg = uiimage(rightPanel, ...
                'Position', [startX1 yBase-yPos-imgH imgW imgH]);
            app.FilterGaussianBlurBtn = uibutton(rightPanel, 'state', 'Text', '', ...
                'Position', [startX1 yBase-yPos-imgH-btnH-3 imgW btnH], ...
                'BackgroundColor', [0.8 0.8 0.8], ...
                'ValueChangedFcn', @(btn, event) app.updateButtonColor(btn));
            uilabel(rightPanel, 'Text', 'Gaussian Blur', ...
                'Position', [startX1 yBase-yPos-imgH-btnH-labelH-6 imgW labelH], ...
                'HorizontalAlignment', 'center', 'FontSize', 9);

            app.FilterSharpenImg = uiimage(rightPanel, ...
                'Position', [startX1+imgW+colGap yBase-yPos-imgH imgW imgH]);
            app.FilterSharpenBtn = uibutton(rightPanel, 'state', 'Text', '', ...
                'Position', [startX1+imgW+colGap yBase-yPos-imgH-btnH-3 imgW btnH], ...
                'BackgroundColor', [0.8 0.8 0.8], ...
                'ValueChangedFcn', @(btn, event) app.updateButtonColor(btn));
            uilabel(rightPanel, 'Text', 'Sharpen', ...
                'Position', [startX1+imgW+colGap yBase-yPos-imgH-btnH-labelH-6 imgW labelH], ...
                'HorizontalAlignment', 'center', 'FontSize', 9);

            app.FilterSobelImg = uiimage(rightPanel, ...
                'Position', [startX1+2*(imgW+colGap) yBase-yPos-imgH imgW imgH]);
            app.FilterSobelBtn = uibutton(rightPanel, 'state', 'Text', '', ...
                'Position', [startX1+2*(imgW+colGap) yBase-yPos-imgH-btnH-3 imgW btnH], ...
                'BackgroundColor', [0.8 0.8 0.8], ...
                'ValueChangedFcn', @(btn, event) app.updateButtonColor(btn));
            uilabel(rightPanel, 'Text', 'Edges (Sobel)', ...
                'Position', [startX1+2*(imgW+colGap) yBase-yPos-imgH-btnH-labelH-6 imgW labelH], ...
                'HorizontalAlignment', 'center', 'FontSize', 9);
            yPos = yPos + imgH + btnH + labelH + rowGap;

            % ROW 2: 3 filters (Canny, Emboss, HistEq)
            app.FilterCannyImg = uiimage(rightPanel, ...
                'Position', [startX1 yBase-yPos-imgH imgW imgH]);
            app.FilterCannyBtn = uibutton(rightPanel, 'state', 'Text', '', ...
                'Position', [startX1 yBase-yPos-imgH-btnH-3 imgW btnH], ...
                'BackgroundColor', [0.8 0.8 0.8], ...
                'ValueChangedFcn', @(btn, event) app.updateButtonColor(btn));
            uilabel(rightPanel, 'Text', 'Canny', ...
                'Position', [startX1 yBase-yPos-imgH-btnH-labelH-6 imgW labelH], ...
                'HorizontalAlignment', 'center', 'FontSize', 9);

            app.FilterEmbossImg = uiimage(rightPanel, ...
                'Position', [startX1+imgW+colGap yBase-yPos-imgH imgW imgH]);
            app.FilterEmbossBtn = uibutton(rightPanel, 'state', 'Text', '', ...
                'Position', [startX1+imgW+colGap yBase-yPos-imgH-btnH-3 imgW btnH], ...
                'BackgroundColor', [0.8 0.8 0.8], ...
                'ValueChangedFcn', @(btn, event) app.updateButtonColor(btn));
            uilabel(rightPanel, 'Text', 'Emboss', ...
                'Position', [startX1+imgW+colGap yBase-yPos-imgH-btnH-labelH-6 imgW labelH], ...
                'HorizontalAlignment', 'center', 'FontSize', 9);

            app.FilterHistEqImg = uiimage(rightPanel, ...
                'Position', [startX1+2*(imgW+colGap) yBase-yPos-imgH imgW imgH]);
            app.FilterHistEqBtn = uibutton(rightPanel, 'state', 'Text', '', ...
                'Position', [startX1+2*(imgW+colGap) yBase-yPos-imgH-btnH-3 imgW btnH], ...
                'BackgroundColor', [0.8 0.8 0.8], ...
                'ValueChangedFcn', @(btn, event) app.updateButtonColor(btn));
            uilabel(rightPanel, 'Text', 'Hist. Equal.', ...
                'Position', [startX1+2*(imgW+colGap) yBase-yPos-imgH-btnH-labelH-6 imgW labelH], ...
                'HorizontalAlignment', 'center', 'FontSize', 9);
            yPos = yPos + imgH + btnH + labelH + rowGap;

            % ROW 3: 2 filters (Adaptive Hist, Noise Reduction) - centered
            totalW3 = 2*imgW + colGap;
            startX3 = (560 - totalW3) / 2;
            
            app.FilterAdaptHistImg = uiimage(rightPanel, ...
                'Position', [startX3 yBase-yPos-imgH imgW imgH]);
            app.FilterAdaptHistBtn = uibutton(rightPanel, 'state', 'Text', '', ...
                'Position', [startX3 yBase-yPos-imgH-btnH-3 imgW btnH], ...
                'BackgroundColor', [0.8 0.8 0.8], ...
                'ValueChangedFcn', @(btn, event) app.updateButtonColor(btn));
            uilabel(rightPanel, 'Text', 'Adaptive Hist.', ...
                'Position', [startX3 yBase-yPos-imgH-btnH-labelH-6 imgW labelH], ...
                'HorizontalAlignment', 'center', 'FontSize', 9);

            app.FilterNoiseReductionImg = uiimage(rightPanel, ...
                'Position', [startX3+imgW+colGap yBase-yPos-imgH imgW imgH]);
            app.FilterNoiseReductionBtn = uibutton(rightPanel, 'state', 'Text', '', ...
                'Position', [startX3+imgW+colGap yBase-yPos-imgH-btnH-3 imgW btnH], ...
                'BackgroundColor', [0.8 0.8 0.8], ...
                'ValueChangedFcn', @(btn, event) app.updateButtonColor(btn));
            uilabel(rightPanel, 'Text', 'Noise Reduct.', ...
                'Position', [startX3+imgW+colGap yBase-yPos-imgH-btnH-labelH-6 imgW labelH], ...
                'HorizontalAlignment', 'center', 'FontSize', 9);
            yPos = yPos + imgH + btnH + labelH + 25;

            % Apply Filters button
            app.ApplyFiltersButton = uibutton(rightPanel, 'push', ...
                'Text', '✓ Apply Selected Filters', ...
                'Position', [150 yBase-yPos-30 250 32], ...
                'BackgroundColor', [0.8 0.9 1], 'FontWeight', 'bold', ...
                'FontSize', 11, 'ButtonPushedFcn', @app.ApplyFiltersButtonPushed);
            yPos = yPos + 50;

            % Separator
            uilabel(rightPanel, 'Text', '', 'Position', [20 yBase-yPos 520 2], 'BackgroundColor', [0.6 0.6 0.6]);
            yPos = yPos + 20;

            % === SECTION 6: IMAGE INFO ===
            uilabel(rightPanel, 'Text', '═══ IMAGE INFO ═══', ...
                'Position', [20 yBase-yPos 520 25], 'FontWeight', 'bold', ...
                'FontSize', 13, 'HorizontalAlignment', 'center', ...
                'BackgroundColor', [0.85 0.90 0.95]);
            yPos = yPos + 35;

            app.ImageInfoText = uitextarea(rightPanel, 'Value', "", ...
                'Position', [20 yBase-yPos-200 520 200], ...
                'Editable', 'off', 'FontSize', 10);
            yPos = yPos + 215;

            % Separator
            uilabel(rightPanel, 'Text', '', 'Position', [20 yBase-yPos 520 2], 'BackgroundColor', [0.6 0.6 0.6]);
            yPos = yPos + 20;

            % === SECTION 7: HISTORY ===
            uilabel(rightPanel, 'Text', '═══ HISTORY LOG ═══', ...
                'Position', [20 yBase-yPos 520 25], 'FontWeight', 'bold', ...
                'FontSize', 13, 'HorizontalAlignment', 'center', ...
                'BackgroundColor', [0.85 0.90 0.95]);
            yPos = yPos + 35;

            app.HistoryText = uitextarea(rightPanel, 'Value', "", ...
                'Position', [20 yBase-yPos-250 520 250], ...
                'Editable', 'off', 'FontSize', 9);
            yPos = yPos + 260;

            app.ExportLogButton = uibutton(rightPanel, 'push', 'Text', '📄 Export Log', ...
                'Position', [20 yBase-yPos-30 140 30], ...
                'BackgroundColor', [0.9 0.95 1], 'FontWeight', 'bold', ...
                'ButtonPushedFcn', @app.ExportLogButtonPushed);
            yPos = yPos + 45;

            % Final spacer to ensure scroll works
            uilabel(rightPanel, 'Text', '', 'Position', [0 yBase-yPos 1 1], 'Visible', 'off');

        end

    end

end